<?php 
try{
    throw new Exception("Error en la aplicaciÃ³n");  
} catch (Exception $e) {
    echo $e->getMessage();
} finally {
    echo "Finalizando";
}